import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — Aura Lab',
  description: 'Terms of Service for Aura Lab.',
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-3">
      <h2 className="font-sans font-bold text-[#F5F1EA] text-[16px]">{title}</h2>
      <div className="flex flex-col gap-2 font-sans text-[#8A8680] text-[14px] leading-relaxed">
        {children}
      </div>
    </div>
  );
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#07070A] text-[#F5F1EA]">
      <nav className="flex items-center justify-between px-8 py-5 border-b border-[rgba(255,241,234,0.06)]">
        <Link href="/" className="flex items-center gap-2 hover:opacity-70 transition-opacity">
          <div className="w-[13px] h-[13px] rounded-[3px] bg-white" />
          <span className="font-mono text-[12px] text-white tracking-[0.22em] font-bold">AURA LAB</span>
        </Link>
        <Link href="/" className="font-mono text-[11px] text-[#8A8680] hover:text-[#F5F1EA] tracking-[0.15em] transition-colors">
          ← back
        </Link>
      </nav>

      <div className="max-w-2xl mx-auto px-6 py-16 flex flex-col gap-10">
        <div className="flex flex-col gap-2">
          <span className="font-mono text-[10px] text-[#4A4742] tracking-[0.25em]">LEGAL</span>
          <h1 className="font-sans font-black text-white text-4xl tracking-tight">Terms of Service</h1>
          <p className="font-sans text-[#4A4742] text-[13px]">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>By accessing or using Aura Lab ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          <p>We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>Aura Lab is an AI-powered entertainment service that analyzes outfit photos and generates fictional "aura" readings. All results are generated by artificial intelligence and are intended for entertainment purposes only.</p>
          <p>Aura Lab does not provide professional style advice, fashion consulting, or any form of professional assessment.</p>
        </Section>

        <Section title="3. User Accounts and Credits">
          <p>You may create an account using a valid email address or supported third-party authentication provider. You are responsible for maintaining the confidentiality of your account credentials.</p>
          <p>Credits are purchased in-app and are used to unlock full scan results. Credits are non-refundable except where required by applicable law. Credits do not expire.</p>
          <p>We reserve the right to suspend or terminate accounts that violate these terms.</p>
        </Section>

        <Section title="4. Payments and Refunds">
          <p>Payments are processed securely through Stripe. By making a purchase, you authorize us to charge your payment method for the selected credit package.</p>
          <p>All sales are final. Refunds are not provided for purchased credits, except where required by applicable consumer protection laws in your jurisdiction.</p>
          <p>If you experience a billing error, contact us at support@auralab.app within 30 days of the transaction.</p>
        </Section>

        <Section title="5. User Content and Image Uploads">
          <p>When you upload a photo, you grant Aura Lab a limited, non-exclusive license to process that image solely for the purpose of generating your aura reading.</p>
          <p>We do not store uploaded images beyond the duration required to complete your scan. Images are not used to train AI models.</p>
          <p>You represent that you have the right to upload any image you submit, and that the image does not violate any third-party rights or applicable laws.</p>
          <p>Do not upload images that are sexually explicit, depict minors in inappropriate contexts, or violate any applicable laws.</p>
        </Section>

        <Section title="6. Prohibited Conduct">
          <p>You agree not to:</p>
          <ul className="list-disc list-inside flex flex-col gap-1 pl-2">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to reverse engineer, scrape, or exploit the Service</li>
            <li>Upload images of third parties without their consent</li>
            <li>Share, sell, or transfer credits to other users</li>
            <li>Circumvent any access controls or rate limits</li>
            <li>Use the Service in any way that could damage or overburden our infrastructure</li>
          </ul>
        </Section>

        <Section title="7. Disclaimer of Warranties">
          <p>The Service is provided "as is" and "as available" without warranties of any kind. We do not warrant that the Service will be uninterrupted, error-free, or that results will be accurate or suitable for any purpose.</p>
          <p>AI-generated readings are fictional and for entertainment only. Do not make real-world decisions based on Aura Lab results.</p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>To the maximum extent permitted by law, Aura Lab and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.</p>
          <p>Our total liability for any claim arising from these terms or your use of the Service shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
        </Section>

        <Section title="9. Governing Law">
          <p>These terms are governed by applicable law. Any disputes shall be resolved through binding arbitration, except where prohibited by law.</p>
        </Section>

        <Section title="10. Contact">
          <p>Questions about these terms? Contact us at <span className="text-[#F5F1EA]">support@auralab.app</span></p>
        </Section>

        <div className="pt-6 border-t border-[rgba(255,241,234,0.06)] flex gap-6">
          <Link href="/privacy" className="font-mono text-[10px] text-[#4A4742] hover:text-[#8A8680] tracking-[0.14em] transition-colors">PRIVACY POLICY</Link>
          <Link href="/" className="font-mono text-[10px] text-[#4A4742] hover:text-[#8A8680] tracking-[0.14em] transition-colors">BACK TO HOME</Link>
        </div>
      </div>
    </main>
  );
}
